#spring.application.name=notes
#spring.main.allow-bean-definition-overriding=true
#spring.jpa.generate-ddl=false
#spring.jpa.hibernate.ddl-auto=none


server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MyDBforDiploma
    username: root
    password: "!ForbiddenFruit19911905"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false


#spring:
#  application:
#    name: notes
#  main:
#    allow-bean-definition-overriding: true
#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#    open-in-view: false








#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus
  endpoint:
    health:
      show-details: always
#      status:
#        http-mapping:
#          up: 207
#        prometheus:
#          enabled: true
#        endpoints:
#          web:
#            exposure:
#              include: '*'
#        metrics:
#          export:
#            prometheus:
#              enabled: true
#        info:
#          env:
#            enabled: true


